//! Emoji catalog for the compose picker: a curated set, each with searchable
//! keywords. Not the full Unicode set — the ~350 people actually reach for.

pub const CATALOG: &[(&str, &[(&str, &str)])] = &[
    (
        "Smileys",
        &[
            ("😀", "grin happy"),
            ("😄", "smile happy laugh"),
            ("😆", "laughing squint"),
            ("😂", "joy tears laugh lol"),
            ("🤣", "rofl rolling laugh lmao"),
            ("😊", "blush smile"),
            ("🙂", "slight smile"),
            ("😉", "wink"),
            ("😍", "heart eyes love"),
            ("🥰", "hearts in love"),
            ("😘", "kiss blow"),
            ("😜", "wink tongue zany"),
            ("🤪", "zany crazy wild"),
            ("😝", "tongue squint"),
            ("🤑", "money mouth rich"),
            ("🤗", "hug"),
            ("🤔", "thinking hmm"),
            ("🤨", "raised eyebrow suspicious"),
            ("😐", "neutral meh"),
            ("😑", "expressionless"),
            ("🙄", "eye roll"),
            ("😏", "smirk"),
            ("😪", "sleepy tired"),
            ("😴", "sleeping zzz"),
            ("😌", "relieved calm"),
            ("😔", "pensive sad"),
            ("🥺", "pleading puppy eyes beg"),
            ("😢", "cry tear sad"),
            ("😭", "sobbing bawling cry loud"),
            ("😤", "huffing frustrated triumph"),
            ("😠", "angry mad"),
            ("😡", "rage furious mad"),
            ("🤬", "cursing swearing angry"),
            ("🤯", "mind blown exploding"),
            ("😳", "flushed embarrassed"),
            ("🥵", "hot sweating heat"),
            ("🥶", "cold freezing frozen"),
            ("😱", "scream fear shock"),
            ("😨", "fearful scared"),
            ("😰", "anxious sweat nervous"),
            ("🤒", "sick thermometer ill"),
            ("🤮", "vomit puke sick"),
            ("🤧", "sneeze tissue sick"),
            ("😷", "mask sick"),
            ("🥴", "woozy drunk dizzy"),
            ("😵", "dizzy knocked out"),
            ("🤠", "cowboy yeehaw"),
            ("🥳", "party celebrate birthday"),
            ("😎", "sunglasses cool"),
            ("🤓", "nerd glasses geek"),
            ("🧐", "monocle inspect fancy"),
            ("😈", "devil smiling imp evil"),
            ("👿", "devil angry imp"),
            ("🤡", "clown"),
            ("💀", "skull dead"),
            ("☠️", "skull crossbones dead"),
            ("👻", "ghost boo"),
            ("👽", "alien ufo"),
            ("🤖", "robot bot"),
            ("💩", "poop"),
            ("😺", "cat smile"),
            ("😹", "cat joy laugh"),
            ("🙈", "see no evil monkey"),
            ("🙉", "hear no evil monkey"),
            ("🙊", "speak no evil monkey"),
        ],
    ),
    (
        "Gestures",
        &[
            ("👍", "thumbs up like +1 yes"),
            ("👎", "thumbs down dislike -1 no"),
            ("👌", "ok okay perfect"),
            ("🤌", "pinched fingers chef italian"),
            ("✌️", "peace victory"),
            ("🤞", "crossed fingers luck hope"),
            ("🤟", "love you sign"),
            ("🤘", "rock horns metal"),
            ("🤙", "call me shaka hang loose"),
            ("👈", "point left"),
            ("👉", "point right"),
            ("👆", "point up"),
            ("👇", "point down"),
            ("☝️", "point up one"),
            ("✋", "raised hand stop high five"),
            ("🖐️", "hand splayed five"),
            ("👋", "wave hello bye"),
            ("🤚", "raised back of hand"),
            ("💪", "muscle flex strong bicep"),
            ("🖕", "middle finger rude"),
            ("✊", "fist raised power"),
            ("👊", "fist bump punch"),
            ("🤛", "left fist bump"),
            ("🤜", "right fist bump"),
            ("👏", "clap applause"),
            ("🙌", "raised hands praise hooray"),
            ("👐", "open hands"),
            ("🤲", "palms up cupped"),
            ("🤝", "handshake deal agreement"),
            ("🙏", "pray please thanks folded hands"),
            ("✍️", "writing hand"),
            ("💅", "nail polish sassy"),
            ("🤳", "selfie"),
            ("🫡", "salute respect o7"),
            ("👀", "eyes looking sus"),
            ("👁️", "eye"),
            ("🧠", "brain smart bigbrain"),
            ("🦾", "mechanical arm robot strong"),
            ("👑", "crown king queen"),
        ],
    ),
    (
        "Animals & Nature",
        &[
            ("🐶", "dog puppy"),
            ("🐱", "cat kitten"),
            ("🐭", "mouse"),
            ("🐹", "hamster"),
            ("🐰", "rabbit bunny"),
            ("🦊", "fox"),
            ("🐻", "bear"),
            ("🐼", "panda"),
            ("🐨", "koala"),
            ("🐯", "tiger"),
            ("🦁", "lion"),
            ("🐮", "cow moo"),
            ("🐷", "pig oink"),
            ("🐸", "frog pepe"),
            ("🐵", "monkey"),
            ("🐔", "chicken"),
            ("🐧", "penguin"),
            ("🐦", "bird tweet"),
            ("🦆", "duck quack"),
            ("🦅", "eagle bird"),
            ("🦉", "owl"),
            ("🐺", "wolf"),
            ("🐗", "boar"),
            ("🐴", "horse"),
            ("🦄", "unicorn"),
            ("🐝", "bee buzz"),
            ("🐛", "bug caterpillar"),
            ("🦋", "butterfly"),
            ("🐌", "snail slow"),
            ("🐢", "turtle slow"),
            ("🐍", "snake"),
            ("🦖", "trex dinosaur"),
            ("🐙", "octopus"),
            ("🦀", "crab rave"),
            ("🐟", "fish"),
            ("🐬", "dolphin"),
            ("🐳", "whale"),
            ("🦈", "shark"),
            ("🐊", "crocodile alligator"),
            ("🦍", "gorilla harambe"),
            ("🐘", "elephant"),
            ("🦒", "giraffe"),
            ("🐪", "camel"),
            ("🦙", "llama alpaca"),
            ("🐐", "goat greatest"),
            ("🦥", "sloth slow lazy"),
            ("🦝", "raccoon trash panda"),
            ("🌵", "cactus"),
            ("🌲", "evergreen tree"),
            ("🌴", "palm tree beach"),
            ("🍀", "clover luck four leaf"),
            ("🌹", "rose flower"),
            ("🌻", "sunflower"),
            ("🌸", "cherry blossom flower"),
            ("🌚", "new moon face dark"),
            ("🌝", "full moon face"),
            ("⭐", "star"),
            ("🌟", "glowing star"),
            ("⚡", "lightning zap bolt"),
            ("🔥", "fire lit flame hot"),
            ("🌈", "rainbow"),
            ("☀️", "sun sunny"),
            ("🌧️", "rain cloud"),
            ("⛈️", "thunderstorm lightning"),
            ("❄️", "snowflake cold snow"),
            ("🌊", "wave ocean water"),
        ],
    ),
    (
        "Food & Drink",
        &[
            ("🍎", "apple red"),
            ("🍌", "banana"),
            ("🍉", "watermelon"),
            ("🍇", "grapes"),
            ("🍓", "strawberry"),
            ("🍒", "cherries"),
            ("🍑", "peach butt"),
            ("🥭", "mango"),
            ("🍍", "pineapple"),
            ("🥥", "coconut"),
            ("🥑", "avocado"),
            ("🍆", "eggplant"),
            ("🥕", "carrot"),
            ("🌽", "corn"),
            ("🌶️", "hot pepper spicy"),
            ("🥔", "potato"),
            ("🍞", "bread loaf"),
            ("🥐", "croissant"),
            ("🥨", "pretzel"),
            ("🧀", "cheese"),
            ("🥚", "egg"),
            ("🍳", "fried egg cooking"),
            ("🥓", "bacon"),
            ("🥩", "steak meat"),
            ("🍗", "chicken leg drumstick"),
            ("🍔", "burger hamburger"),
            ("🍟", "fries french"),
            ("🍕", "pizza slice"),
            ("🌭", "hot dog"),
            ("🥪", "sandwich"),
            ("🌮", "taco"),
            ("🌯", "burrito"),
            ("🍜", "ramen noodles soup"),
            ("🍝", "spaghetti pasta"),
            ("🍣", "sushi"),
            ("🍤", "shrimp fried tempura"),
            ("🍚", "rice bowl"),
            ("🍿", "popcorn movie"),
            ("🧂", "salt salty"),
            ("🍦", "ice cream soft serve"),
            ("🍩", "donut doughnut"),
            ("🍪", "cookie"),
            ("🎂", "birthday cake"),
            ("🍰", "cake shortcake slice"),
            ("🧁", "cupcake"),
            ("🍫", "chocolate bar"),
            ("🍬", "candy"),
            ("☕", "coffee hot"),
            ("🍵", "tea green"),
            ("🥤", "cup straw soda"),
            ("🧋", "boba bubble tea"),
            ("🍺", "beer mug"),
            ("🍻", "beers cheers clink"),
            ("🍷", "wine glass"),
            ("🥃", "whiskey tumbler"),
            ("🍸", "cocktail martini"),
            ("🍾", "champagne bottle pop"),
        ],
    ),
    (
        "Activities",
        &[
            ("⚽", "soccer football"),
            ("🏀", "basketball"),
            ("🏈", "football american"),
            ("⚾", "baseball"),
            ("🎾", "tennis"),
            ("🏐", "volleyball"),
            ("🎱", "eight ball pool billiards"),
            ("🏓", "ping pong table tennis"),
            ("🏸", "badminton"),
            ("🥊", "boxing glove"),
            ("⛳", "golf flag hole"),
            ("🎣", "fishing pole"),
            ("🎽", "running shirt"),
            ("🛹", "skateboard"),
            ("⛷️", "skiing"),
            ("🏂", "snowboard"),
            ("🏋️", "weight lifting gym"),
            ("🚴", "cycling bike"),
            ("🏆", "trophy winner champion"),
            ("🥇", "gold medal first"),
            ("🥈", "silver medal second"),
            ("🥉", "bronze medal third"),
            ("🎖️", "military medal"),
            ("🎗️", "reminder ribbon"),
            ("🎫", "ticket"),
            ("🎪", "circus tent"),
            ("🎭", "theater masks drama"),
            ("🎨", "art palette paint"),
            ("🎬", "clapper movie film"),
            ("🎤", "microphone sing karaoke"),
            ("🎧", "headphones music"),
            ("🎼", "sheet music score"),
            ("🎹", "piano keyboard"),
            ("🥁", "drum"),
            ("🎷", "saxophone"),
            ("🎺", "trumpet"),
            ("🎸", "guitar"),
            ("🎻", "violin"),
            ("🎲", "dice game random"),
            ("♟️", "chess pawn"),
            ("🎯", "dart bullseye target"),
            ("🎳", "bowling"),
            ("🎮", "video game controller gaming"),
            ("🕹️", "joystick arcade"),
            ("🎰", "slot machine gamble"),
            ("🧩", "puzzle piece"),
        ],
    ),
    (
        "Travel & Places",
        &[
            ("🚗", "car red automobile"),
            ("🚕", "taxi"),
            ("🚌", "bus"),
            ("🏎️", "race car fast"),
            ("🚓", "police car"),
            ("🚑", "ambulance"),
            ("🚒", "fire truck"),
            ("🚚", "truck delivery"),
            ("🚜", "tractor"),
            ("🛵", "scooter moped"),
            ("🏍️", "motorcycle"),
            ("🚲", "bicycle bike"),
            ("🚨", "siren alarm police light"),
            ("🚀", "rocket ship launch"),
            ("🛸", "ufo flying saucer"),
            ("✈️", "airplane flight"),
            ("🚁", "helicopter"),
            ("⛵", "sailboat"),
            ("🚢", "ship cruise"),
            ("⚓", "anchor"),
            ("🚂", "train locomotive"),
            ("🚦", "traffic light"),
            ("🗿", "moai stone head"),
            ("🗽", "statue of liberty"),
            ("🗼", "tokyo tower"),
            ("🏰", "castle"),
            ("🏠", "house home"),
            ("🏢", "office building"),
            ("🏥", "hospital"),
            ("🏦", "bank"),
            ("🏝️", "desert island beach"),
            ("🏔️", "mountain snow"),
            ("🌋", "volcano"),
            ("🏕️", "camping tent"),
            ("🌃", "night city stars"),
            ("🌆", "cityscape dusk"),
            ("🌍", "earth globe world"),
        ],
    ),
    (
        "Objects",
        &[
            ("⌚", "watch time"),
            ("📱", "phone mobile iphone"),
            ("💻", "laptop computer"),
            ("🖥️", "desktop computer monitor"),
            ("⌨️", "keyboard"),
            ("🖱️", "mouse computer"),
            ("🖨️", "printer"),
            ("💾", "floppy disk save"),
            ("💿", "cd disc"),
            ("📷", "camera photo"),
            ("📹", "video camera"),
            ("🎥", "movie camera film"),
            ("📺", "tv television"),
            ("📻", "radio"),
            ("🔊", "speaker loud volume"),
            ("🔇", "muted speaker silence"),
            ("🔔", "bell notification"),
            ("🔕", "bell muted no notifications"),
            ("📢", "loudspeaker announcement"),
            ("💡", "light bulb idea"),
            ("🔦", "flashlight torch"),
            ("🕯️", "candle"),
            ("🔋", "battery"),
            ("🔌", "plug electric"),
            ("🧲", "magnet"),
            ("🔧", "wrench tool"),
            ("🔨", "hammer tool"),
            ("🛠️", "hammer wrench tools fixing"),
            ("⚙️", "gear settings cog"),
            ("🧰", "toolbox"),
            ("🔩", "nut bolt screw"),
            ("⚖️", "balance scale justice"),
            ("🔗", "link chain"),
            ("⛓️", "chains"),
            ("🔪", "knife blade"),
            ("⚔️", "crossed swords battle"),
            ("🛡️", "shield defense"),
            ("🔫", "water pistol gun"),
            ("💣", "bomb explosion"),
            ("🧨", "dynamite firecracker tnt"),
            ("💊", "pill medicine"),
            ("💉", "syringe shot needle"),
            ("🧬", "dna genetics"),
            ("🔬", "microscope science"),
            ("🔭", "telescope astronomy"),
            ("📚", "books study"),
            ("📖", "open book reading"),
            ("📝", "memo note writing"),
            ("✏️", "pencil"),
            ("📌", "pushpin pin"),
            ("📎", "paperclip clippy"),
            ("✂️", "scissors cut"),
            ("📦", "package box shipping"),
            ("📬", "mailbox mail"),
            ("💰", "money bag rich"),
            ("💸", "money wings flying spending"),
            ("💳", "credit card"),
            ("💎", "gem diamond"),
            ("🔑", "key"),
            ("🔒", "locked padlock"),
            ("🔓", "unlocked open"),
            ("🚪", "door"),
            ("🪑", "chair sit"),
            ("🛏️", "bed sleep"),
            ("🚽", "toilet"),
            ("🧻", "toilet paper roll"),
            ("🧼", "soap clean"),
            ("🗑️", "trash can wastebasket garbage"),
        ],
    ),
    (
        "Symbols",
        &[
            ("❤️", "red heart love"),
            ("🧡", "orange heart"),
            ("💛", "yellow heart"),
            ("💚", "green heart"),
            ("💙", "blue heart"),
            ("💜", "purple heart"),
            ("🖤", "black heart"),
            ("🤍", "white heart"),
            ("🤎", "brown heart"),
            ("💔", "broken heart sad"),
            ("❣️", "heart exclamation"),
            ("💕", "two hearts"),
            ("💞", "revolving hearts"),
            ("💓", "beating heart"),
            ("💗", "growing heart"),
            ("💖", "sparkling heart"),
            ("💘", "heart arrow cupid"),
            ("💝", "heart ribbon gift"),
            ("💯", "hundred 100 perfect"),
            ("💢", "anger symbol"),
            ("💥", "collision boom explosion"),
            ("💫", "dizzy stars"),
            ("💦", "sweat droplets splash"),
            ("💨", "dash wind gone fast"),
            ("🕳️", "hole"),
            ("💤", "zzz sleep"),
            ("✨", "sparkles shiny"),
            ("🎉", "party popper tada celebrate"),
            ("🎊", "confetti ball"),
            ("🎈", "balloon"),
            ("🎁", "gift present wrapped"),
            ("🏁", "checkered flag finish race"),
            ("🚩", "red flag warning"),
            ("🏳️", "white flag surrender"),
            ("❓", "question mark"),
            ("❗", "exclamation mark"),
            ("⁉️", "interrobang what"),
            ("⚠️", "warning caution"),
            ("🚫", "prohibited no banned"),
            ("✅", "check mark done yes"),
            ("❌", "cross mark x no wrong"),
            ("⭕", "circle correct"),
            ("➕", "plus add"),
            ("➖", "minus subtract"),
            ("➗", "divide"),
            ("♾️", "infinity forever"),
            ("🔞", "18 underage no minors"),
            ("📵", "no phones"),
            ("🆗", "ok button"),
            ("🆒", "cool button"),
            ("🆕", "new button"),
            ("🆓", "free button"),
            ("🔆", "brightness bright"),
            ("🎵", "music note"),
            ("🎶", "music notes melody"),
            ("♻️", "recycle"),
            ("⚜️", "fleur de lis"),
            ("🔱", "trident"),
            ("🔰", "beginner japan"),
            ("💬", "speech bubble chat"),
            ("💭", "thought bubble thinking"),
            ("🗨️", "left speech bubble"),
            ("🕐", "clock one oclock time"),
        ],
    ),
];

/// All (emoji, keywords) pairs whose keywords match the query, or the full
/// catalog when the query is empty (grouped by category for display).
pub fn search(query: &str) -> Vec<(&'static str, &'static str)> {
    let q = query.trim().to_lowercase();
    CATALOG
        .iter()
        .flat_map(|(_, list)| list.iter())
        .filter(|(_, keywords)| q.is_empty() || keywords.contains(q.as_str()))
        .copied()
        .collect()
}
