//! Generates an embedded icon registry from assets/icons/*.svg.
//! Drop a new .svg in that folder and it becomes available as
//! `Icon { name: "<file-stem>" }` after a rebuild.

use std::fmt::Write;

fn main() {
    println!("cargo:rerun-if-changed=assets/icons");
    println!("cargo:rerun-if-changed=assets/app.ico");
    embed_exe_icon();
    let out_dir = std::env::var("OUT_DIR").unwrap();

    let mut entries: Vec<(String, String)> = std::fs::read_dir("assets/icons")
        .expect("assets/icons directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "svg"))
        .map(|e| {
            let name = e.path().file_stem().unwrap().to_string_lossy().into_owned();
            let content = std::fs::read_to_string(e.path()).expect("readable svg");
            (name, content.trim().to_owned())
        })
        .collect();
    entries.sort();

    let mut code = String::from(
        "/// Generated by build.rs from assets/icons/*.svg — do not edit.\n\
         pub fn icon_svg(name: &str) -> &'static str {\n    match name {\n",
    );
    for (name, content) in &entries {
        writeln!(code, "        {name:?} => {content:?},").unwrap();
    }
    code.push_str("        _ => \"\",\n    }\n}\n");

    std::fs::write(format!("{out_dir}/icons_gen.rs"), code).unwrap();
}

/// Give the executable its icon and its name. Windows reads both from the
/// binary's resource table: without the icon the taskbar and Explorer show
/// the generic "unknown application" page, and without the strings the
/// Properties → Details tab said ProductName "client", CompanyName "" —
/// which is what an unsigned 45 MB exe that captures the screen and
/// replaces itself looks like to Defender's heuristics, right before it
/// quarantines it. Named binaries score better; signed ones better still.
#[cfg(windows)]
fn embed_exe_icon() {
    let mut res = winresource::WindowsResource::new();
    if std::path::Path::new("assets/app.ico").exists() {
        res.set_icon("assets/app.ico");
    }
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_default();
    res.set("ProductName", "NotDiscord");
    res.set("FileDescription", "NotDiscord — chat, voice and video for your crew");
    res.set("CompanyName", "NotDiscord");
    res.set("LegalCopyright", "Copyright (c) 2026 switchb and the NotDiscord contributors. MIT licence.");
    res.set("OriginalFilename", "NotDiscord.exe");
    res.set("InternalName", "NotDiscord");
    res.set("ProductVersion", &version);
    res.set("FileVersion", &version);
    {
        if let Err(e) = res.compile() {
            // Not fatal: an iconless build still runs, and failing here would
            // block every build on a machine without the resource compiler.
            println!("cargo:warning=could not embed the exe icon: {e}");
        }
    }
}

#[cfg(not(windows))]
fn embed_exe_icon() {}
