//! Generates an embedded icon registry from assets/icons/*.svg.
//! Drop a new .svg in that folder and it becomes available as
//! `Icon { name: "<file-stem>" }` after a rebuild.

use std::fmt::Write;

fn main() {
    println!("cargo:rerun-if-changed=assets/icons");
    println!("cargo:rerun-if-changed=assets/app.ico");
    embed_exe_icon();
    let out_dir = std::env::var("OUT_DIR").unwrap();

    let mut entries: Vec<(String, String)> = std::fs::read_dir("assets/icons")
        .expect("assets/icons directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "svg"))
        .map(|e| {
            let name = e.path().file_stem().unwrap().to_string_lossy().into_owned();
            let content = std::fs::read_to_string(e.path()).expect("readable svg");
            (name, content.trim().to_owned())
        })
        .collect();
    entries.sort();

    let mut code = String::from(
        "/// Generated by build.rs from assets/icons/*.svg — do not edit.\n\
         pub fn icon_svg(name: &str) -> &'static str {\n    match name {\n",
    );
    for (name, content) in &entries {
        writeln!(code, "        {name:?} => {content:?},").unwrap();
    }
    code.push_str("        _ => \"\",\n    }\n}\n");

    std::fs::write(format!("{out_dir}/icons_gen.rs"), code).unwrap();
}

/// Give the executable its icon. Windows reads this from the binary's
/// resource table, not from anything at runtime — without it the taskbar and
/// Explorer fall back to the generic "unknown application" page.
#[cfg(windows)]
fn embed_exe_icon() {
    if std::path::Path::new("assets/app.ico").exists() {
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/app.ico");
        if let Err(e) = res.compile() {
            // Not fatal: an iconless build still runs, and failing here would
            // block every build on a machine without the resource compiler.
            println!("cargo:warning=could not embed the exe icon: {e}");
        }
    }
}

#[cfg(not(windows))]
fn embed_exe_icon() {}
