//! Generates an embedded icon registry from assets/icons/*.svg.
//! Drop a new .svg in that folder and it becomes available as
//! `Icon { name: "<file-stem>" }` after a rebuild.

use std::fmt::Write;

fn main() {
    println!("cargo:rerun-if-changed=assets/icons");
    let out_dir = std::env::var("OUT_DIR").unwrap();

    let mut entries: Vec<(String, String)> = std::fs::read_dir("assets/icons")
        .expect("assets/icons directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "svg"))
        .map(|e| {
            let name = e.path().file_stem().unwrap().to_string_lossy().into_owned();
            let content = std::fs::read_to_string(e.path()).expect("readable svg");
            (name, content.trim().to_owned())
        })
        .collect();
    entries.sort();

    let mut code = String::from(
        "/// Generated by build.rs from assets/icons/*.svg — do not edit.\n\
         pub fn icon_svg(name: &str) -> &'static str {\n    match name {\n",
    );
    for (name, content) in &entries {
        writeln!(code, "        {name:?} => {content:?},").unwrap();
    }
    code.push_str("        _ => \"\",\n    }\n}\n");

    std::fs::write(format!("{out_dir}/icons_gen.rs"), code).unwrap();
}
